version: '3.7'

networks:
    kong-net:
        external: false
        driver: bridge

services:
    ###############################################
    # Postgres: The database used by Kong and KongA
    ###############################################
    kong-database:
        image: postgres:9.6
        environment:
            POSTGRES_DB: ${KONG_DB_NAME}
            POSTGRES_USER: ${KONG_DB_USER}
            POSTGRES_PASSWORD: ${KONG_DB_PASSWORD}
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "${KONG_DB_USER:-kong}" ]
            interval: 30s
            timeout: 30s
            retries: 3
        restart: on-failure
        stdin_open: true
        tty: true
        ports:
            - "5432:5432"
        networks:
            - kong-net
        volumes:
            - ./kong_data:/var/lib/postgresql/data

    #######################################
    # Kong database migration
    #######################################
    kong-migration:
        image: ${KONG_VERSION}
        command: kong migrations bootstrap
        depends_on:
            - kong-database
        environment:
            KONG_DATABASE: postgres
            KONG_PG_DATABASE: ${KONG_DB_NAME}
            KONG_PG_HOST: ${KONG_DB_HOST}
            KONG_PG_USER: ${KONG_DB_USER}
            KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
        networks:
            - kong-net
        restart: on-failure

    #######################################
    # Kong: RUN migration
    #######################################
    kong-migration-up:
        image: ${KONG_VERSION}
        command: kong migrations up && kong migrations finish
        depends_on:
            - kong-database
        environment:
            KONG_DATABASE: postgres
            KONG_PG_DATABASE: ${KONG_DB_NAME}
            KONG_PG_HOST: ${KONG_DB_HOST}
            KONG_PG_USER: ${KONG_DB_USER}
            KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
        networks:
            - kong-net
        restart: on-failure

    #######################################
    # Kong API Gateway
    #######################################
    kong:
        image: ${KONG_VERSION}
        user: "${KONG_USER:-kong}"
        depends_on:
            - kong-database
        environment:
            KONG_DATABASE: postgres
            KONG_PG_DATABASE: ${KONG_DB_NAME}
            KONG_PG_HOST: ${KONG_DB_HOST:-kong-database}
            KONG_PG_USER: ${KONG_DB_USER}
            KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: '0.0.0.0:8001'
        networks:
            - kong-net
        ports:
            - "8000:8000/tcp"
            - "8001:8001/tcp"
            - "8443:8443/tcp"
        healthcheck:
            test: [ "CMD", "kong", "health" ]
            interval: 10s
            timeout: 10s
            retries: 10
        restart: on-failure


    #######################################
    # KongA: Kong GUI
    #######################################
    konga:
        image: ${KONGA_VERSION}
        depends_on:
            - kong
        ports:
            - ${KONGA_PORT}:1337
        networks:
            - kong-net
        environment:
            - NODE_ENV=production
